import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "getting-started" }],
    },
    {
      type: "category",
      label: "Installation",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "installation" }],
    },
    {
      type: "category",
      label: "Desktop Environments",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "desktop-environments" }],
    },
    {
      type: "category",
      label: "Applications",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "applications" }],
    },
    {
      type: "category",
      label: "Samsung Features",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "samsung-features" }],
    },
    {
      type: "category",
      label: "Performance",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "performance" }],
    },
    {
      type: "category",
      label: "Development",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "development" }],
    },
    {
      type: "category",
      label: "Troubleshooting",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "troubleshooting" }],
    },
    {
      type: "category",
      label: "FAQ",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "faq" }],
    },
    {
      type: "category",
      label: "Glossary",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "glossary" }],
    },
    {
      type: "category",
      label: "Downloads",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "downloads" }],
    },
    {
      type: "category",
      label: "Contributing",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "contributing" }],
    },
  ],
};

export default sidebars;
