import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  docsSidebar: [
    "intro",
    {
      type: "category",
      label: "Quick Start",
      collapsed: false,
      link: { type: "doc", id: "quick-start/overview" },
      items: [
        "quick-start/install-termux",
        "quick-start/install-ubuntu",
        "quick-start/install-desktop",
        "quick-start/first-launch",
        "quick-start/samsung-dex",
      ],
    },
    {
      type: "category",
      label: "Learn",
      link: { type: "generated-index", description: "Understand the concepts, software, and hardware behind Android Desktop Linux." },
      items: [
        {
          type: "category",
          label: "Core Concepts",
          collapsed: false,
          link: { type: "generated-index" },
          items: [{ type: "autogenerated", dirName: "learn/concepts" }],
        },
        {
          type: "category",
          label: "Software Stack",
          link: { type: "generated-index" },
          items: [{ type: "autogenerated", dirName: "learn/software" }],
        },
        {
          type: "category",
          label: "Hardware",
          link: { type: "generated-index" },
          items: [{ type: "autogenerated", dirName: "learn/hardware" }],
        },
      ],
    },
    {
      type: "category",
      label: "Reference",
      link: { type: "generated-index", description: "Searchable technical reference for commands, configuration, and compatibility." },
      items: [
        {
          type: "category",
          label: "Command Reference",
          link: { type: "generated-index" },
          items: [{ type: "autogenerated", dirName: "reference/commands" }],
        },
        {
          type: "category",
          label: "Configuration",
          link: { type: "generated-index" },
          items: [{ type: "autogenerated", dirName: "reference/configuration" }],
        },
        {
          type: "category",
          label: "Compatibility",
          link: { type: "generated-index" },
          items: [{ type: "autogenerated", dirName: "reference/compatibility" }],
        },
      ],
    },
    {
      type: "category",
      label: "Installation",
      link: { type: "generated-index", description: "Detailed installation guides for all supported devices." },
      items: [
        {
          type: "category",
          label: "Common Installation",
          collapsed: false,
          link: { type: "generated-index" },
          items: [{ type: "autogenerated", dirName: "installation/common" }],
        },
        {
          type: "category",
          label: "Samsung Devices",
          link: { type: "generated-index" },
          items: [{ type: "autogenerated", dirName: "installation/samsung" }],
        },
        {
          type: "category",
          label: "Google Pixel",
          link: { type: "generated-index" },
          items: [{ type: "autogenerated", dirName: "installation/pixel" }],
        },
        {
          type: "category",
          label: "OnePlus",
          link: { type: "generated-index" },
          items: [{ type: "autogenerated", dirName: "installation/oneplus" }],
        },
      ],
    },
    {
      type: "category",
      label: "Desktop Environments",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "desktop-environments" }],
    },
    {
      type: "category",
      label: "Applications",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "applications" }],
    },
    {
      type: "category",
      label: "Samsung",
      link: { type: "generated-index", description: "Samsung DeX integration and Galaxy-specific features." },
      items: [{ type: "autogenerated", dirName: "samsung" }],
    },
    {
      type: "category",
      label: "Performance",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "performance" }],
    },
    {
      type: "category",
      label: "Troubleshooting",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "troubleshooting" }],
    },
    {
      type: "category",
      label: "Downloads",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "downloads" }],
    },
    {
      type: "category",
      label: "FAQ",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "faq" }],
    },
    {
      type: "category",
      label: "Glossary",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "glossary" }],
    },
    {
      type: "category",
      label: "Contributing",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "contributing" }],
    },
    {
      type: "category",
      label: "Release Notes",
      link: { type: "generated-index" },
      items: [{ type: "autogenerated", dirName: "release-notes" }],
    },
  ],
};

export default sidebars;
